#
#  Author: Hari Sekhon
#  Date: 2024-08-21 04:11:40 +0200 (Wed, 21 Aug 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/HariSekhon
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# Designed to validate the master Jenkinsfile in my Jenkins repo:
#
#   https://github.com/HariSekhon/Jenkins

---
name: Update Profile

on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/update_profile.yaml  # this workflow

  workflow_call:

  schedule:
    # - min interval is 5 mins
    # - scheduling may be delayed during periods of high load on GitHub Actions infra, such as at the top of every hour
    # - '*' is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'

permissions:
  contents: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  # needs all 4 of these Git committer and author variables
  GIT_AUTHOR_NAME: Hari Sekhon
  GIT_AUTHOR_EMAIL: harisekhon@gmail.com
  GIT_COMMITTER_NAME: Hari Sekhon
  GIT_COMMITTER_EMAIL: harisekhon@gmail.com
  GH_TOKEN: ${{ github.token }}
  PATH: /usr/bin:bash-tools/github
  #DEBUG: 1

jobs:
  update_profile_counters:
    name: Update Profile Counters
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - name: Checkout harisekhon repo
        uses: actions/checkout@v3

      - name: Checkout bash-tools repo
        uses: actions/checkout@v3
        with:
          repository: HariSekhon/DevOps-Bash-tools
          #ref: master         # unset for default branch in case it changes in future
          #submodules: recursive  # don't need the submodules for just this script, save time
          path: bash-tools

      - name: Update Repo Count
        run: |
          repo_count="$(github_user_repos_count.sh "$GITHUB_REPOSITORY_OWNER")"

          sed -i "s|badge/Repos-[[:digit:]]\+-|badge/Repos-${repo_count}-|" README.md

      - name: Update Follower Count
        run: |
          follower_count="$(github_user_followers.sh "$GITHUB_REPOSITORY_OWNER")"

          sed -i "s|badge/Followers-[[:digit:]]\+-|badge/Followers-${follower_count}-|" README.md

      - name: Update Repos Stars Count
        run: |
          star_count="$(github_user_repos_stars.sh "$GITHUB_REPOSITORY_OWNER")"

          sed -i "s|badge/Stars-[[:digit:]]\+-|badge/Stars-${star_count}-|" README.md

      - name: Update Repos Forks Count
        run: |
          fork_count="$(github_user_repos_forks.sh "$GITHUB_REPOSITORY_OWNER")"

          sed -i "s|badge/Forks-[[:digit:]]\+-|badge/Forks-${fork_count}-|" README.md

      - name: Update CI/CD Build Count
        run: |
          readme="$(curl -sS https://raw.githubusercontent.com/HariSekhon/CI-CD/master/README.md)"

          build_count="$(grep -Eo 'badge/CI%2FCD%20Builds-[[:digit:]]+-' | sed 's/-$//; s/.*-//')"

          sed -i "s|badge/Forks-[[:digit:]]\+-|badge/CI%2FCD%20Builds-${build_count}-|" README.md

      - name: Git Diff
        run: |
          git diff

      - name: Git Add
        run: |
          git add README.md

      - name: Git Commit
        id: commit
        run: |
          if ! git diff-index --quiet HEAD; then
            git commit -m "updated profile counters" README.md
            echo "::set-output name=committed::true"
          fi

      - name: Git Push
        if: steps.commit.outputs.committed == 'true'
        run: |
          git push
